category_choices = {
  ('Electronics', 'Electronics'),
  ('Cars', 'Cars'),
  ('Furniture', 'Furniture'),
  ('Mobiles', 'Mobiles'),
  ('Bikes', 'Bikes'),
  ('Books&Sports', 'Books&Sports'),
  ('Fashion', 'Fashion'),
  ('other', 'other')
  }


state_choices = {
  ('AP', 'Andhra Pradesh'),
  ('AR', 'Arunachal Pradesh'),
  ('AS', 'Assam'),
  ('BR', 'Bihar'),
  ('CG', 'Chhattisgarh'),
  ('GA', 'Goa'),
  ('GJ', 'Gujarat'),
  ('HP', 'Haryana'),
  ('JH', 'Jharkhand'),
  ('KA', 'Karnataka'),
  ('KL', 'Kerala'),
  ('MP', 'Madhya Pradesh'),
  ('MH', 'Maharashtra'),
  ('MN', 'Manipur'),
  ('ML', 'Meghalaya'),
  ('MZ', 'Mizoram'),
  ('NL', 'Nagaland'),
  ('OD', 'Odisha'),
  ('PB', 'Punjab'),
  ('RJ', 'Rajasthan'),
  ('MI', 'Sikkim'),
  ('TN', 'Tamil Nadu'),
  ('TS', 'Telangana'),
  ('TR', 'Tripura'),
  ('UP', 'Uttar Pradesh'),
  ('UK', 'Uttarakhand'),
  ('WB', 'West Bengal'),
}
